[workspace]
resolver = "2"
members = [ "rp2040-kbd", "rp2040-kbd-lib"]

[workspace.dependencies]
rp2040-kbd-lib = { path = "rp2040-kbd-lib" }
arrayvec = { version = "0.7.4", default-features = false }
bitvec = { version = "1.0.1", default-features = false }
cortex-m-rt = "0.7.3"
critical-section = "1.1.2"
embedded-graphics = "0.8.1"
embedded-hal = "1.0.0"
fugit = "0.3.7"
heapless = "0.8.0"
nb = "1.1"
panic-halt= "0.2.0"
paste = "1.0.14"
pio-uart = { git = "https://github.com/MarcusGrass/pio-uart", rev = "5c8bee6" }
liatris = { git = "https://github.com/MarcusGrass/rp-hal-boards", rev = "e6a7e03" }
rp2040-hal = "0.10.0"
ssd1306 = "0.8.4"
usb-device = "0.3.2"
usbd-hid = "0.7.0"
usbd-serial = "0.2.1"
