[graph]
targets = [
    { triple = "thumbv6m-none-eabi" },
]

[advisories]
ignore = [
    # proc-macro-error unmaintained
    "RUSTSEC-2024-0370",
    # paste unmaintained
    "RUSTSEC-2024-0436",
]

[bans]
multiple-versions = "deny"
deny = []
skip = [

    # cortex-m has a bunch of outdated deps
    { name = "bitfield", version = "0.13.2" },
    { name = "bitfield", version = "0.14.0" },
    { name = "hashbrown", version = "0.13.2" },
    { name = "embedded-hal", version = "0.2.7" },
    { name = "nb", version = "0.1.3" },
    { name = "syn", version = "1.0.109" },
]

[sources]
allow-git = [
    "https://github.com/MarcusGrass/rp-hal-boards",
    "https://github.com/MarcusGrass/rp-hal",
    "https://github.com/MarcusGrass/pio-uart",
    "https://github.com/MarcusGrass/usb-device",
]

[licenses]
confidence-threshold = 1.0
# I'd like to know if they pop into my dependency graph
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "MIT",
]
exceptions = [
    { name = "rp2040-kbd", allow = ["GPL-3.0"] },
    { name = "rp2040-kbd-lib", allow = ["GPL-3.0"] },
    { name = "unicode-ident", allow = ["Unicode-3.0"] },
]
